### ISSUE TITLE
Bug: not working after latest update of `winbar`

### ISSUE THREAD

**Issue by lalitmee** [nvim-lualine/lualine.nvim#749] opened 2022-07-23 06:53 UTC
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Just update to the latest `lualine.nvim`

### Expected behaviour
It should work without any error.

### Actual behaviour
Getting this error as soon as the `nvim` loads
```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua .../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'nvim_win_set_option'
	.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: in function 'setter_fn'
	.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:48: in function 'set_opt'
	.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:72: in function 'set'
	...e/nvim/site/pack/packer/opt/lualine.nvim/lua/lualine.lua:349: in function <...e/nvim/site/pack/packer/opt/lualine.nvim/lua/lualine.lua:305>
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:110: Vim(call):E5108: Error executing lua .../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'cmd'
	...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
	[string ":lua"]:1: in main chunk
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: lualine: Failed to refresh statusline:
.../packer/opt/lualine.nvim/lua/lualine/utils/nvim_opts.lua:75: E539: Illegal character < >
stack traceback:
	[C]: in function 'error'
	...pack/packer/opt/lualine.nvim/lua/lualine/utils/utils.lua:204: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

### Aditional information

My config:
```lua
lualine.setup({
  options = {
    theme = "auto",
    globalstatus = true,
    section_separators = { left = "", right = "" },
    component_separators = { left = "", right = "" },
  },
  sections = {
    lualine_a = {
      {
        "mode",
        fmt = function(str)
          return "<" .. str:sub(1, 1) .. ">"
        end,
      },
    },
    lualine_b = {
      {
        "branch",
        icon = "",
      },
    },
    lualine_c = {
      { "diff" },
      "%=%",
      { "filetype", icon_only = true },
      {
        custom_fname,
        path = 1,
        color = "LualineFileName",
        symbols = {
          modified = " []",
          readonly = " []",
        },
      },
      {
        get_client_name,
        color = "LualineSessionName",
        separator = { right = "", left = "" },
      },
    },
    lualine_x = {
      {
        "diagnostics",
        sources = { "nvim_diagnostic" },
        symbols = {
          error = " ",
          warn = " ",
          hint = " ",
          info = " ",
        },
      },
      { get_trailing_whitespace },
    },
    lualine_y = { { "progress" } },
    lualine_z = { { "location", icon = "" } },
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { { "filename", path = 0 } },
    lualine_x = { "filetype" },
    lualine_z = { "location" },
  },
  extensions = {
    "man",
    "nvim-tree",
    "quickfix",
    "toggleterm",
  },
})
```

**Comment by shadmansaleh** [comment] 2022-07-23 07:05
Pretty sure it's just duplicate of https://github.com/nvim-lualine/lualine.nvim/issues/746 . But since you didn't bother adding a isolated minimal_reproduction config as stated in the issue template not even the config you're using I'm just gonna ignore this issue.  Do follow the issue template while opening issue .Otherwise it's not possible for me to help you resolve your issue.

**Closed by shadmansaleh** 2022-07-23 07:05 UTC
Labels: bug

**Comment by lalitmee** [comment] 2022-07-23 13:15
@shadmansaleh, sorry. I tried to add a my config but when I was adding something inside `<details>` tag it was not showing up in the preview. Otherwise I also know that it helps a lot when we have a minimal config to reproduce the issue. 

I am not sure what was the problem in the bug template.

**Comment by shadmansaleh** [comment] 2022-07-23 13:27
In that case It's better to remove the details tag. I was a bit rude there. The thing is issues without any kind of info about the environment the issue occurred in are really annoying .

Like I said earlier . It's a duplicate of #746. Your `%=%` in lualine_c is  the reason . See my comment on that issue https://github.com/nvim-lualine/lualine.nvim/issues/746#issuecomment-1192694168

**Comment by lalitmee** [comment] 2022-07-23 13:57
@shadmansaleh, I was thinking of removing that too. But thought that it will not be professional. So didn't

And thanks for pointing the bug. I resolved the issue. Its fixed.

Thank you so much.
