### ISSUE TITLE
Feat: 

### ISSUE THREAD

**Issue by muppi090909** [nvim-lualine/lualine.nvim#585] opened 2022-02-23 09:32 UTC
### Requested feature

Show total word count in status line.

### Motivation

Usually it is easier to know generally how big it is.
For example I was writing an essay and I had a page limit of 2 so it is much easier to know if it is around 2 pages with the word count.

**Comment by shadmansaleh** [comment] 2022-02-23 10:37
duplicate of #328 

try this https://github.com/nvim-lualine/lualine.nvim/issues/328#issuecomment-911530142

**Closed** 2022-02-23 11:00 UTC
Labels: duplicate, new feature
