### ISSUE TITLE
Bug: diff not working and lsp progress animation

### ISSUE THREAD

**Issue by melsiir** [nvim-lualine/lualine.nvim#527] opened 2022-01-03 20:09 UTC
### Self Checks

- [ X] I'm using the latest lualine.
- [X ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

ins_left({
   'diff',
   -- Is it me or the symbol for modified us really weird
   symbols = { added = ' ', modified = '柳 ', removed = ' ' },
   diff_color = {
     added = { fg = colors.green },
     modified = { fg = colors.orange },
     removed = { fg = colors.red },
   },
   -- cond = conditions.hide_in_width,
 })

### Expected behaviour

Showing diff indicators when modifing or delete or adding lines

### Actual behaviour
Not showing any thing off diff stuff

### Minimal config to reproduce the issue
This packer config
use({
    "nvim-lualine/lualine.nvim",
    requires = { "rlch/github-notifications.nvim" },
    -- event = "VimEnter",
    --
    config = [[require('custom.plugins.evil_lualine')]],
    after = "nvim-web-devicons",
  })

<details>
<summary>Config</summary>
Everything working fine except the diff stuff and lsp progress animation 
![Screenshot_٢٠٢٢٠١٠٣-٢١٥٨١٦_Termux](https://user-images.githubusercontent.com/73516767/147975304-dcefce54-fddf-41d1-b004-70e7ecab84f9.jpg)

call plug#begin("/data/data/com.termux/files/home/test/.local/share/nvim/plugged")
" Your plugins go here like
Plug 'nvim-lualine/lualine.nvim'

Plug 'kyazdani42/nvim-web-devicons'

call plug#end()

" Your Viml part of config goes here
" colorscheme onedark

lua << END
-- Your lua part of config goes here

require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
    component_separators = { left = '', right = ''},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'diagnostics'},
    lualine_c = {'filename'},
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}

END

</details>

**Comment by shadmansaleh** [comment] 2022-01-04 01:11
I can't reproduce it with the info you've provided . It's working fine for me with your config . You'll have to provide a minimal config with only essential plugins that can reproduce the issue , so we can make sure some other plugin isn't causing the issue. You can use  https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh to create an isolated nvim config.

Also did you save the file after making changes ? You need to save it for diff to update.

**Comment by melsiir** [comment] 2022-01-04 05:27
> I can't reproduce it with the info you've provided . It's working fine for me with your config . You'll have to provide a minimal config with only essential plugins that can reproduce the issue , so we can make sure some other plugin isn't causing the issue. You can use https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh to create an isolated nvim config.
> 
> Also did you save the file after making changes ? You need to save it for diff to update.

I provided isolated confi up there ☝️

**Comment by melsiir** [comment] 2022-01-04 05:49
It didn't work till I add diff source

local function diff_source()
  local gitsigns = vim.b.gitsigns_status_dict
  if gitsigns then
    return {
      added = gitsigns.added,
      modified = gitsigns.changed,
      removed = gitsigns.removed
    }
  end
end



ins_left { 'diff',source = diff_source}


But still lsp-progress don't work

**Comment by shadmansaleh** [comment] 2022-01-04 06:41
> I provided isolated confi up there ☝️

packer config won't work because start plugins installed by packer still gets loaded even if you remove them from your plugin_spec and if packer_compiled file is still present it'll load everything even without the spec :/

Besides I still can't reproduce it .

Also you do have `git` installed right ?

the `diff_source` that you're using depends on `gitsigns` it can't work on isolated config unless you explicitly install `gitsigns`

**Comment by melsiir** [comment] 2022-01-04 18:06
> > I provided isolated confi up there ☝️
> 
> packer config won't work because start plugins installed by packer still gets loaded even if you remove them from your plugin_spec and if packer_compiled file is still present it'll load everything even without the spec :/
> 
> Besides I still can't reproduce it .
> 
> Also you do have `git` installed right ?
> 
> the `diff_source` that you're using depends on `gitsigns` it can't work on isolated config unless you explicitly install `gitsigns`


I was using feline and git diff was working properly without adding gitsign source but now with lualine it won't work till I add gitsign source and now it work well is that anything bad or had any security or performance issue

**Comment by shadmansaleh** [comment] 2022-01-05 02:27
### Questions:
- Do you have `git` cli installed?

lualine doesn't rely on external sources for diff . But has `git_source` option to intrigate external sources  @l=====ike `gitsigns` . When no source is provided lualine uses =[internal source](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/diff/git_diff.lua) that gets diff data from `git` cli . If you have other plugins installed that provide diff data it's better to use them as source. In case of feline it directly gets diff data from gitsigns . So unless you have gitsigns installed diff doesn't work there.

**Comment by melsiir** [comment] 2022-01-05 04:46
> ### Questions:
> * Do you have `git` cli installed?
> 
> lualine doesn't rely on external sources for diff . But has `git_source` option to intrigate external sources like `gitsigns` . When no source is provided lualine uses =[internal source](https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/components/diff/git_diff.lua) that gets diff data from `git` cli . If you have other plugins installed that provide diff data it's better to use them as source. In case of feline it directly gets diff data from gitsigns . So unless you have gitsigns installed diff doesn't work there.

I have git but I don't have git-cli .


Regardless of lsp-progress animation it doesn't work does because I am using termux or it deprecated ?

This my config :

local function lsp_progress(_, is_active)
  if not is_active then
    return
  end
  local messages = vim.lsp.util.get_progress_messages()
  if #messages == 0 then
    return ""
  end
  -- dump(messages)
  local status = {}
  for _, msg in pairs(messages) do
    local title = ""
    if msg.title then
      title = msg.title
    end
    -- if msg.message then
    --   title = title .. " " .. msg.message
    -- end
    table.insert(status, (msg.percentage or 0) .. "%% " .. title)
  end
  local spinners = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" }
  local ms = vim.loop.hrtime() / 1000000
  local frame = math.floor(ms / 120) % #spinners
  return table.concat(status, "  ") .. " " .. spinners[frame + 1]
end

vim.cmd("au User LspProgressUpdate let &ro = &ro")

ins-left ({
'lsp-progress'
})


------

I tried to run this command in my nvim command :vim.lsp.util.get_progress_messages()

Buti get this error :

Cannot open file "util.get_progress_messages()"
E480: No match: lsp

though I have pyright and tssever and vscode extracted bins and they all work well


Do you have any explanation

**Comment by shadmansaleh** [comment] 2022-01-11 11:36
I have tested on termux and both branch & lsp-progress is working there . There might be something wrong with your termux setup 🤷‍♂️

I'm closing this as I haven't been able to reproduce it nor do I see any reason for these to not work .

**Closed by shadmansaleh** 2022-01-11 11:36 UTC
Labels: bug, can't reproduce
