### ISSUE TITLE
help wanted:  is it possible to set negative padding?

### ISSUE THREAD

**Issue by cstsunfu** [nvim-lualine/lualine.nvim#665] opened 2022-04-25 13:08 UTC
### How to set for negative padding
![image](https://user-images.githubusercontent.com/24812659/165093377-ef1a7c78-18e2-4adc-9d7a-d79ff4c2223e.png)
As the picture show, I set the windows split vertical character as the right vertical '▕', there is a blank space between two windows, it doesn't affect functionality, but it's pretty ugly. 

I have try   `padding = { right = -1 }`, but nothing changed.

Is there a way to set a negative padding?

**Comment by cstsunfu** [comment] 2022-04-25 17:26
![image](https://user-images.githubusercontent.com/24812659/165141216-bedb2187-0585-4ae0-b846-ee55647fb385.png)
Oh, the question is caused by the no highlight blank between two vertical windows.  How to set the content of this part?

**Comment by shadmansaleh** [comment] 2022-04-28 12:53
No padding can't be negative.

The issue is duplicate of #615 & #469

follow comment [here](https://github.com/nvim-lualine/lualine.nvim/issues/615#issuecomment-1072318608)

**Closed** 2022-04-28 12:54 UTC
Labels: duplicate, wontfix
