### ISSUE TITLE
How to stop lualine from flickering when selecting options in the coc menu?

### ISSUE THREAD

**Issue by skamsie** [nvim-lualine/lualine.nvim#1313] opened 2024-10-21 21:39 UTC
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or PRs.

Each time I navigate through the coc menu with Ctrl-P Ctrl-N my status line flickers. I can see it is because with each movement in the coc menu it briefly enters command mode so the status line updates from 'normal' to 'command' and viceversa... Is there a way to prevent this?

I am coming from a vim config where I was using the [vim-airline](https://github.com/vim-airline/vim-airline) plugin and this does not happen...

https://github.com/user-attachments/assets/1d411240-0afb-4048-bf38-620906eb801d

**Comment by shadmansaleh** [comment] 2024-11-01 06:45
Can you check if #1316 fixes the flickering?

**Comment by skamsie** [comment] 2024-11-01 08:34
@shadmansaleh thanks for trying to fix, but unfortunately it does not fix it for me, the behaviour is exactly the same. Not only that, but it seems to have a weird side effect as well: I can briefly see the default vim start screen before seeing my 'alpha' start screen.

**Comment by shadmansaleh** [comment] 2024-11-01 09:25
ok I'll look at it later then. It_ would be better if you could provide e minimal config. Setting up coc.nvim to test this is annoying since I don't use it myself.

**Comment by skamsie** [comment] 2024-11-01 13:38
it reproduces with the defaults (assuming lazy):

_~/config/nvim/lua/plugins/coc.lua_
```lua
-- in case of error
-- :call coc#util#install()
return {
  'neoclide/coc.nvim',
  config = function()
    vim.g.coc_global_extensions = { 'coc-lua' }
  end
}
```

_~/.config/nvim/coc-settings.json_
```json
{
  "suggest.minTriggerInputLength": 2,
  "suggest.snippetIndicator": ">",
  "diagnostic.enable": true,
  "inlayHint.enable": false,
  "Lua.diagnostics.globals": ["vim"]
}
```

**Comment by shadmansaleh** [comment] 2024-11-01 15:04
Try out #1316 again. I think this should be fixed now.

**Comment by shadmansaleh** [comment] 2024-11-01 16:16
I've never been able to reproduce that side effect on my side. I think we can avoid the debounce now with autocommand refresh getting removed.

see if it works correctly now for you.

**Comment by skamsie** [comment] 2024-11-01 16:36
> I've never been able to reproduce that side effect on my side

might be something else in my config then... thanks for fixing

**Closed** 2024-11-08 02:42 UTC
Labels: bug
